import type { Dataset } from "./datasets";

export const seedDatasets: Dataset[] = [
  {
    id: "dvf",
    title: "Demandes de valeurs foncières",
    provider: "DGFiP · data.gouv.fr",
    sourceType: "Gouvernement",
    description: "Transactions immobilières enregistrées en France : prix, dates, surfaces, nature des biens et localisation cadastrale.",
    domain: "Immobilier",
    country: "France",
    period: "5 dernières années",
    formats: ["CSV", "TXT"],
    license: "Licence Ouverte 2.0",
    update: "Semestrielle",
    score: 96,
    size: "≈ 400 Mo / an",
    access: "Téléchargement direct",
    variables: ["valeur foncière", "date de mutation", "type de local", "surface", "commune"],
    url: "https://www.data.gouv.fr/datasets/demandes-de-valeurs-foncieres",
    tags: ["Meilleur choix", "Source officielle"],
    accent: "#6d5dfc",
  },
  {
    id: "wdi-youth",
    title: "Chômage des jeunes (15–24 ans)",
    provider: "Banque mondiale · WDI",
    sourceType: "Institution",
    description: "Taux de chômage annuel des jeunes, estimations modélisées de l’OIT, avec ventilation par sexe et couverture mondiale.",
    domain: "Économie",
    country: "Monde",
    period: "1991–2025",
    formats: ["API", "CSV", "XLSX"],
    license: "CC BY 4.0",
    update: "Annuelle",
    score: 95,
    size: "Léger",
    access: "API sans clé",
    variables: ["pays", "année", "taux total", "taux femmes", "taux hommes"],
    url: "https://data.worldbank.org/indicator/SL.UEM.1524.ZS",
    tags: ["Meilleure API", "Power BI"],
    accent: "#0d9f85",
  },
  {
    id: "open-meteo",
    title: "Open-Meteo Historical Weather",
    provider: "Open-Meteo",
    sourceType: "API",
    description: "Données météorologiques historiques et prévisions mondiales, requêtables par coordonnées et sans clé pour un usage non commercial.",
    domain: "Météo",
    country: "Monde",
    period: "1940–aujourd’hui",
    formats: ["API", "JSON", "CSV"],
    license: "CC BY 4.0",
    update: "Temps réel",
    score: 92,
    size: "À la demande",
    access: "API sans clé",
    variables: ["température", "précipitations", "vent", "humidité", "rayonnement"],
    url: "https://open-meteo.com/en/docs/historical-weather-api",
    tags: ["Temps réel", "Développeurs"],
    accent: "#3387e8",
  },
  {
    id: "eurostat",
    title: "Eurostat Data Browser",
    provider: "Commission européenne",
    sourceType: "Institution",
    description: "Catalogue statistique européen couvrant la population, l’économie, l’environnement, l’industrie et les territoires.",
    domain: "Statistiques",
    country: "Europe",
    period: "Variable",
    formats: ["API", "CSV", "XLSX", "JSON"],
    license: "Réutilisation Eurostat",
    update: "Selon l’indicateur",
    score: 91,
    size: "Variable",
    access: "API et export",
    variables: ["pays", "période", "indicateur", "unité", "valeur"],
    url: "https://ec.europa.eu/eurostat/databrowser/",
    tags: ["Source officielle", "Très documenté"],
    accent: "#f0a629",
  },
  {
    id: "uci-adult",
    title: "Adult Census Income",
    provider: "UCI Machine Learning Repository",
    sourceType: "Recherche",
    description: "Jeu de classification de référence visant à prédire si le revenu annuel d’une personne dépasse 50 000 dollars.",
    domain: "Machine learning",
    country: "États-Unis",
    period: "1994",
    formats: ["CSV"],
    license: "CC BY 4.0",
    update: "Archive stable",
    score: 87,
    size: "48 842 lignes",
    access: "Téléchargement direct",
    variables: ["âge", "éducation", "profession", "heures", "revenu"],
    url: "https://archive.ics.uci.edu/dataset/2/adult",
    tags: ["Machine learning", "Débutants"],
    accent: "#e65e79",
  },
  {
    id: "ilostat",
    title: "ILOSTAT Bulk Data",
    provider: "Organisation internationale du Travail",
    sourceType: "Institution",
    description: "Indicateurs mondiaux du travail : emploi, chômage, salaires, protection sociale et conditions de travail.",
    domain: "Emploi",
    country: "Monde",
    period: "Variable",
    formats: ["CSV", "API"],
    license: "CC BY 4.0",
    update: "Régulière",
    score: 94,
    size: "Variable",
    access: "Téléchargement en masse",
    variables: ["indicateur", "sexe", "âge", "pays", "année", "valeur"],
    url: "https://ilostat.ilo.org/data/bulk/",
    tags: ["Source officielle", "Recherche"],
    accent: "#9365d8",
  },
  {
    id: "recensement-population-insee",
    title: "Recensement de la population",
    provider: "INSEE",
    sourceType: "Gouvernement",
    description: "Statistiques démographiques officielles de la population française : âge, sexe, activité, logement, par commune et département.",
    domain: "Démographie",
    country: "France",
    period: "Mise à jour continue",
    formats: ["CSV", "XLSX"],
    license: "Licence Ouverte 2.0",
    update: "Annuelle",
    score: 93,
    size: "Variable selon le fichier",
    access: "Téléchargement direct",
    variables: ["population", "âge", "sexe", "commune", "catégorie socio-professionnelle"],
    url: "https://www.insee.fr/fr/statistiques",
    tags: ["Source officielle", "Démographie"],
    accent: "#2a9d8f",
  },
  {
    id: "who-gho",
    title: "Global Health Observatory",
    provider: "OMS (WHO)",
    sourceType: "Institution",
    description: "Indicateurs de santé mondiaux : espérance de vie, mortalité, maladies, systèmes de santé, pour plus de 190 pays.",
    domain: "Santé",
    country: "Monde",
    period: "1990–aujourd’hui",
    formats: ["API", "CSV", "JSON"],
    license: "CC BY-NC-SA 3.0 IGO",
    update: "Régulière",
    score: 94,
    size: "Variable",
    access: "API et export",
    variables: ["pays", "année", "indicateur de santé", "valeur"],
    url: "https://www.who.int/data/gho",
    tags: ["Source officielle", "Santé"],
    accent: "#e63946",
  },
  {
    id: "nasa-power",
    title: "NASA POWER",
    provider: "NASA",
    sourceType: "API",
    description: "Données solaires et météorologiques mondiales pour l’agriculture, l’énergie et le bâtiment, dérivées de la ré-analyse satellite.",
    domain: "Énergie",
    country: "Monde",
    period: "1981–aujourd’hui",
    formats: ["API", "CSV", "JSON"],
    license: "Domaine public (NASA Open Data)",
    update: "Quotidienne",
    score: 90,
    size: "À la demande",
    access: "API sans clé",
    variables: ["rayonnement solaire", "température", "précipitations", "vent"],
    url: "https://power.larc.nasa.gov/",
    tags: ["Temps réel", "Développeurs"],
    accent: "#f4a261",
  },
  {
    id: "noaa-climate-data",
    title: "NOAA Climate Data Online",
    provider: "NOAA",
    sourceType: "API",
    description: "Observations climatiques et météorologiques historiques aux États-Unis et dans le monde : températures, précipitations, tempêtes.",
    domain: "Météo",
    country: "États-Unis",
    period: "1850–aujourd’hui",
    formats: ["API", "CSV"],
    license: "Domaine public",
    update: "Quotidienne",
    score: 91,
    size: "Variable",
    access: "API avec clé gratuite",
    variables: ["station", "date", "température", "précipitations"],
    url: "https://www.ncei.noaa.gov/cdo-web/",
    tags: ["Source officielle", "Historique"],
    accent: "#457b9d",
  },
  {
    id: "us-census-acs",
    title: "American Community Survey",
    provider: "US Census Bureau",
    sourceType: "Gouvernement",
    description: "Enquête démographique et socio-économique continue sur la population américaine : revenus, logement, emploi, éducation.",
    domain: "Démographie",
    country: "États-Unis",
    period: "Estimations annuelles (1 et 5 ans)",
    formats: ["API", "CSV"],
    license: "Domaine public",
    update: "Annuelle",
    score: 92,
    size: "Variable",
    access: "API et export",
    variables: ["revenu médian", "population", "logement", "éducation"],
    url: "https://www.census.gov/programs-surveys/acs",
    tags: ["Source officielle", "Démographie"],
    accent: "#1d3557",
  },
  {
    id: "fbi-crime-data-explorer",
    title: "Crime Data Explorer",
    provider: "FBI",
    sourceType: "Gouvernement",
    description: "Statistiques officielles de la criminalité aux États-Unis, remontées par les agences locales et fédérales.",
    domain: "Sécurité",
    country: "États-Unis",
    period: "1985–aujourd’hui",
    formats: ["API", "CSV", "JSON"],
    license: "Domaine public",
    update: "Annuelle",
    score: 88,
    size: "Variable",
    access: "API et export",
    variables: ["type de crime", "état", "année", "taux pour 100 000 habitants"],
    url: "https://cde.ucr.cjis.gov/",
    tags: ["Source officielle", "Sécurité"],
    accent: "#6d597a",
  },
  {
    id: "un-comtrade",
    title: "UN Comtrade",
    provider: "Organisation des Nations Unies",
    sourceType: "Institution",
    description: "Base de données mondiale des statistiques de commerce international, par pays, produit et partenaire commercial.",
    domain: "Commerce international",
    country: "Monde",
    period: "1962–aujourd’hui",
    formats: ["API", "CSV"],
    license: "Réutilisation ONU",
    update: "Mensuelle",
    score: 89,
    size: "Variable",
    access: "API et export",
    variables: ["pays déclarant", "partenaire", "produit", "valeur échangée"],
    url: "https://comtradeplus.un.org/",
    tags: ["Source officielle", "Commerce"],
    accent: "#588157",
  },
  {
    id: "oecd-data-explorer",
    title: "OECD Data Explorer",
    provider: "OCDE",
    sourceType: "Institution",
    description: "Statistiques économiques et sociales des pays membres de l’OCDE : PIB, emploi, éducation, environnement, bien-être.",
    domain: "Économie",
    country: "Monde",
    period: "Variable",
    formats: ["API", "CSV", "XLSX"],
    license: "Réutilisation OCDE",
    update: "Régulière",
    score: 92,
    size: "Variable",
    access: "API et export",
    variables: ["pays", "indicateur", "année", "valeur"],
    url: "https://data-explorer.oecd.org/",
    tags: ["Source officielle", "Très documenté"],
    accent: "#bc6c25",
  },
  {
    id: "imf-weo",
    title: "World Economic Outlook",
    provider: "FMI (IMF)",
    sourceType: "Institution",
    description: "Projections et données macroéconomiques mondiales : croissance, inflation, dette publique, balance des paiements.",
    domain: "Économie",
    country: "Monde",
    period: "Semestriel depuis 1980",
    formats: ["XLSX", "CSV"],
    license: "Réutilisation FMI",
    update: "Semestrielle",
    score: 91,
    size: "Léger",
    access: "Téléchargement direct",
    variables: ["pays", "PIB", "inflation", "dette publique"],
    url: "https://www.imf.org/en/Publications/WEO",
    tags: ["Source officielle", "Économie"],
    accent: "#003049",
  },
  {
    id: "global-terrorism-database",
    title: "Global Terrorism Database",
    provider: "START (Université du Maryland)",
    sourceType: "Recherche",
    description: "Base de données recensant plus de 200 000 incidents terroristes dans le monde depuis 1970.",
    domain: "Sécurité",
    country: "Monde",
    period: "1970–aujourd’hui",
    formats: ["XLSX", "CSV"],
    license: "Usage académique",
    update: "Annuelle",
    score: 85,
    size: "≈ 200 000 lignes",
    access: "Téléchargement après inscription",
    variables: ["date", "pays", "type d’attaque", "victimes"],
    url: "https://www.start.umd.edu/gtd/",
    tags: ["Recherche", "Sécurité"],
    accent: "#9b2226",
  },
  {
    id: "openstreetmap-planet",
    title: "OpenStreetMap Planet",
    provider: "OpenStreetMap Foundation",
    sourceType: "API",
    description: "Données cartographiques mondiales collaboratives : routes, bâtiments, points d’intérêt, frontières.",
    domain: "Cartographie",
    country: "Monde",
    period: "Temps réel",
    formats: ["API", "JSON"],
    license: "ODbL",
    update: "Temps réel",
    score: 93,
    size: "> 100 Go (export complet)",
    access: "API et exports complets",
    variables: ["coordonnées", "type de voie", "bâtiment", "point d’intérêt"],
    url: "https://planet.openstreetmap.org/",
    tags: ["Temps réel", "Développeurs"],
    accent: "#2a9d8f",
  },
  {
    id: "gh-archive",
    title: "GH Archive",
    provider: "GH Archive (communauté GitHub)",
    sourceType: "API",
    description: "Archive publique de tous les événements publics GitHub (commits, pull requests, issues) au format horaire.",
    domain: "Technologie",
    country: "Monde",
    period: "2011–aujourd’hui",
    formats: ["JSON", "API"],
    license: "Usage libre",
    update: "Horaire",
    score: 84,
    size: "Plusieurs To (cumulé)",
    access: "Téléchargement direct",
    variables: ["type d’événement", "dépôt", "utilisateur", "date"],
    url: "https://www.gharchive.org/",
    tags: ["Développeurs", "Technologie"],
    accent: "#14213d",
  },
  {
    id: "common-crawl",
    title: "Common Crawl",
    provider: "Common Crawl Foundation",
    sourceType: "Recherche",
    description: "Archive ouverte de pétaoctets de pages web collectées depuis 2008, utilisée pour la recherche en NLP et IA.",
    domain: "Technologie",
    country: "Monde",
    period: "2008–aujourd’hui",
    formats: ["API", "JSON"],
    license: "Usage libre",
    update: "Mensuelle",
    score: 87,
    size: "Plusieurs Po",
    access: "Téléchargement direct (S3)",
    variables: ["URL", "contenu HTML", "métadonnées de crawl"],
    url: "https://commoncrawl.org/",
    tags: ["Recherche", "Machine learning"],
    accent: "#4a4e69",
  },
  {
    id: "kaggle-titanic",
    title: "Titanic - Machine Learning from Disaster",
    provider: "Kaggle",
    sourceType: "Recherche",
    description: "Jeu de données de référence pour l’apprentissage supervisé, prédisant la survie des passagers du Titanic.",
    domain: "Machine learning",
    country: "Monde",
    period: "Historique (1912)",
    formats: ["CSV"],
    license: "CC0",
    update: "Archive stable",
    score: 86,
    size: "891 lignes",
    access: "Téléchargement direct",
    variables: ["âge", "sexe", "classe", "survie"],
    url: "https://www.kaggle.com/c/titanic",
    tags: ["Machine learning", "Débutants"],
    accent: "#e76f51",
  },
  {
    id: "mnist",
    title: "MNIST Database",
    provider: "Yann LeCun, Corinna Cortes",
    sourceType: "Recherche",
    description: "Base d’images de chiffres manuscrits, référence historique pour l’entraînement de modèles de vision par ordinateur.",
    domain: "Machine learning",
    country: "Monde",
    period: "Publié en 1998",
    formats: ["CSV", "API"],
    license: "CC BY-SA 3.0",
    update: "Archive stable",
    score: 88,
    size: "70 000 images",
    access: "Téléchargement direct",
    variables: ["image 28x28 pixels", "label du chiffre"],
    url: "http://yann.lecun.com/exdb/mnist/",
    tags: ["Machine learning", "Débutants"],
    accent: "#8338ec",
  },
  {
    id: "owid-covid",
    title: "COVID-19 Dataset",
    provider: "Our World in Data",
    sourceType: "Institution",
    description: "Suivi mondial de la pandémie de COVID-19 : cas, décès, vaccinations, tests, par pays et dans le temps.",
    domain: "Santé",
    country: "Monde",
    period: "2020–2024",
    formats: ["CSV", "API", "JSON"],
    license: "CC BY 4.0",
    update: "Archive stable",
    score: 90,
    size: "Variable",
    access: "Téléchargement direct",
    variables: ["pays", "date", "cas confirmés", "décès", "vaccinations"],
    url: "https://ourworldindata.org/coronavirus",
    tags: ["Source officielle", "Santé"],
    accent: "#d62828",
  },
  {
    id: "eea-air-quality",
    title: "Qualité de l’air en Europe",
    provider: "Agence européenne pour l’environnement (EEA)",
    sourceType: "Institution",
    description: "Mesures de qualité de l’air issues de milliers de stations de surveillance à travers l’Europe : PM2.5, NO2, ozone.",
    domain: "Environnement",
    country: "Europe",
    period: "Temps réel et historique",
    formats: ["API", "CSV"],
    license: "Réutilisation EEA",
    update: "Temps réel",
    score: 89,
    size: "Variable",
    access: "API et export",
    variables: ["station", "polluant", "concentration", "date"],
    url: "https://www.eea.europa.eu/en/topics/in-depth/air-pollution",
    tags: ["Temps réel", "Environnement"],
    accent: "#52b788",
  },
  {
    id: "iea-data-statistics",
    title: "Data & Statistics",
    provider: "Agence internationale de l’énergie (IEA)",
    sourceType: "Institution",
    description: "Statistiques énergétiques mondiales : production, consommation, mix électrique, émissions liées à l’énergie.",
    domain: "Énergie",
    country: "Monde",
    period: "1971–aujourd’hui",
    formats: ["XLSX", "CSV"],
    license: "Réutilisation IEA (partiellement payant)",
    update: "Régulière",
    score: 87,
    size: "Variable",
    access: "Export (certains jeux payants)",
    variables: ["pays", "source d’énergie", "production", "consommation"],
    url: "https://www.iea.org/data-and-statistics",
    tags: ["Source officielle", "Énergie"],
    accent: "#ffb703",
  },
  {
    id: "sirene-entreprises",
    title: "Base SIRENE des entreprises",
    provider: "INSEE",
    sourceType: "Gouvernement",
    description: "Répertoire national des entreprises et établissements français, avec identifiants SIREN/SIRET et informations légales.",
    domain: "Économie",
    country: "France",
    period: "Mise à jour continue",
    formats: ["CSV", "API"],
    license: "Licence Ouverte 2.0",
    update: "Mensuelle",
    score: 95,
    size: "> 30 millions d’établissements",
    access: "Téléchargement direct et API",
    variables: ["SIREN", "SIRET", "dénomination", "activité", "adresse"],
    url: "https://www.data.gouv.fr/datasets/base-sirene-des-entreprises-et-de-leurs-etablissements-siren-siret/",
    tags: ["Source officielle", "Meilleur choix"],
    accent: "#6d5dfc",
  },
  {
    id: "wikipedia-pageviews",
    title: "Wikipedia Pageviews",
    provider: "Wikimedia Foundation",
    sourceType: "API",
    description: "Statistiques horaires de consultation de tous les articles Wikipedia, par langue et par projet.",
    domain: "Web",
    country: "Monde",
    period: "2015–aujourd’hui",
    formats: ["API", "TXT"],
    license: "CC0",
    update: "Horaire",
    score: 85,
    size: "Plusieurs To (cumulé)",
    access: "Téléchargement direct",
    variables: ["projet", "article", "nombre de vues", "date"],
    url: "https://dumps.wikimedia.org/other/pageviews/",
    tags: ["Temps réel", "Développeurs"],
    accent: "#adb5bd",
  },
  {
    id: "tmdb-api",
    title: "The Movie Database (TMDB)",
    provider: "TMDB",
    sourceType: "API",
    description: "Base de données collaborative sur les films, séries et personnalités du cinéma, avec affiches et métadonnées.",
    domain: "Culture",
    country: "Monde",
    period: "Mise à jour continue",
    formats: ["API", "JSON"],
    license: "Usage libre avec attribution",
    update: "Temps réel",
    score: 86,
    size: "À la demande",
    access: "API avec clé gratuite",
    variables: ["titre", "genre", "date de sortie", "casting", "note"],
    url: "https://www.themoviedb.org/documentation/api",
    tags: ["Développeurs", "Culture"],
    accent: "#f77f00",
  },
  {
    id: "openaq",
    title: "OpenAQ",
    provider: "OpenAQ",
    sourceType: "API",
    description: "Agrégateur mondial en temps réel de mesures de qualité de l’air, issues de sources gouvernementales et de recherche.",
    domain: "Environnement",
    country: "Monde",
    period: "Temps réel",
    formats: ["API", "JSON", "CSV"],
    license: "CC BY 4.0",
    update: "Temps réel",
    score: 88,
    size: "À la demande",
    access: "API sans clé",
    variables: ["ville", "polluant", "concentration", "date"],
    url: "https://openaq.org/",
    tags: ["Temps réel", "Environnement"],
    accent: "#52b788",
  },
  {
    id: "gbif",
    title: "Global Biodiversity Information Facility",
    provider: "GBIF",
    sourceType: "Institution",
    description: "Plus grande base mondiale d’occurrences d’espèces, agrégeant les données de musées, chercheurs et citoyens.",
    domain: "Biodiversité",
    country: "Monde",
    period: "Historique à aujourd’hui",
    formats: ["API", "CSV", "JSON"],
    license: "CC BY 4.0",
    update: "Continue",
    score: 90,
    size: "> 2 milliards d’occurrences",
    access: "API et export",
    variables: ["espèce", "localisation", "date d’observation", "source"],
    url: "https://www.gbif.org/",
    tags: ["Source officielle", "Recherche"],
    accent: "#2a9d8f",
  },
  {
    id: "elections-france",
    title: "Résultats des élections",
    provider: "Ministère de l’Intérieur",
    sourceType: "Gouvernement",
    description: "Résultats officiels des élections françaises (présidentielles, législatives, européennes, municipales) par commune.",
    domain: "Politique",
    country: "France",
    period: "Depuis 2012",
    formats: ["CSV", "XLSX"],
    license: "Licence Ouverte 2.0",
    update: "À chaque scrutin",
    score: 91,
    size: "Variable",
    access: "Téléchargement direct",
    variables: ["commune", "candidat", "voix", "taux de participation"],
    url: "https://www.data.gouv.fr/fr/organizations/ministere-de-linterieur/",
    tags: ["Source officielle", "Politique"],
    accent: "#1d3557",
  },
];
